### ISSUE TITLE
Clarify purpose/description

### ISSUE THREAD

**Issue by ssimontis** [choco14t/store-bounds#4]
Could you please add a clearer description of what this plugin does/why I would want it? If I had to take a guess, it is storing the exact size of the application's window so that it always starts up at your preferred window size. I don't think that would be apparent (assuming I am even correct) to a non-developer, so I would suggest rewriting the README and the description submitted to Inkdrop to something clearer that pitches its purpose if you want more people to adopt it.

**Comment by choco14t** [comment]
Thank you for creating issue. Certainly, current readme is unclearly the purpose and description. Now I'm checking that Inkdrop version 4.x is supported this plugin feature. If it support, this repository will be archived and unpublish plugin.

Sorry for my broken English;)

Thanks.

**Comment by choco14t** [comment]
This plugin feature is supported at version 4.x. 
https://forum.inkdrop.app/t/supported-restore-window-size-and-location/1419/2

So I don't update README because unpublish it. If I will create new plugin, I would like to refer to your advice.
